version: '3'

services:
  nats:
    # image: nats:2.XXXX
    # Replaced this with nightly to get websockets, pin to version as soon as websockets are GA
    image: synadia/nats-server:nightly
    restart: unless-stopped
    volumes:
      - ./infra/config/nats/nats-server.conf:/nats/conf/nats-server.conf
    ports:
      # - '4222:4222' # for clients - port forwarded from router
      # - '6222:6222' # routing port for clustering
      # now using proxy for cors bypass
      # - '18222:8222' # for monitoring/reporting
      - '19222:9222' # for websockets

# Could use a proper dockerfile, for now just use base node image
# CMD: npx local-cors-proxy --proxyUrl http://nats:8222 --port 18222 --proxyPartial '/'
  proxy:
    image: node:14-alpine
    restart: unless-stopped
    depends_on: 
      - nats
    ports:
      - '18222:18222' # for monitoring/reporting
    entrypoint: ''
    command: "npx local-cors-proxy --proxyUrl http://nats:8222 --port 18222 --proxyPartial '/'"
